name: war_room
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  image_gallery_saver: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  ios: true
  image_path: assets/icons/warroom_logo.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"              # fully black background
  image: assets/icons/warroom_logo.png
  android: true
  ios: true
  android_12:
    color: "#000000"
    image: assets/icons/warroom_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
